[package]
name = "fb2epub"
version = "0.1.1"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.53", features = ["derive"] }
epub-builder = "0.8.2"
indicatif = "0.18.3"
quick-xml = { version = "0.38.4", features = ["encoding"]}
tempfile = "3.24.0"
zip = "7.0.0"
